export const FETCH_MODULE_PENDING = 'FETCH_MODULE_PENDING';
export const FETCH_MODULE_SUCCES = 'FETCH_MODULE_SUCCES';
export const FETCH_MODULE_ERROR = "FETCH_MODULE_ERROR";

export const FETCH_MODULES_PENDING = 'FETCH_MODULES_PENDING';
export const FETCH_MODULES_SUCCES = 'FETCH_MODULES_SUCCES';
export const FETCH_MODULES_ERROR = "FETCH_MODULES_ERROR";